services:
  embedding:
    &embedding
    image: truehack:latest
    build: .
    env_file:
      - .env.production
    restart: always
    command: >
      sh -c "python app/embedding.py"

  api:
    <<: *embedding
    ports:
      - "8081:3000"
    labels:
      - traefik.enable=true
      - traefik.http.routers.truehack_mootfrost_dev.rule=Host(`truehack.mootfrost.dev`)
      - traefik.http.services.truehack_mootfrost_dev.loadbalancer.server.port=3000
    command: >
      sh -c "python -m alembic upgrade head && python app/__main__.py"

  db:
    image: postgres:17.4-alpine
    volumes:
      - db_data:/var/lib/postgresql/data/pgdata
    restart: always
    ports:
      - "1877:5432"
    environment:
      POSTGRES_USER: mts
      POSTGRES_PASSWORD: 8f880hWV2525VLX
      POSTGRES_DB: truehack
      PGDATA: /var/lib/postgresql/data/pgdata


  weaviate:
    command:
      - --host
      - 0.0.0.0
      - --port
      - '8080'
      - --scheme
      - http
    image: cr.weaviate.io/semitechnologies/weaviate:1.30.1
    depends_on:
      embedding:
        condition: service_started
    restart: always
    ports:
      - "3002:8080"
      - "50051:50051"
    env_file:
      - .env.production
    environment:
      QUERY_DEFAULTS_ACCEPT_LANGUAGE: "ru"
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: "true"
      PERSISTENCE_DATA_PATH: "/var/lib/weaviate"
      CLUSTER_HOSTNAME: "node1"
      ENABLE_API_BASED_MODULES: 'true'
      DEFAULT_VECTORIZER_MODULE: "text2vec-transformers"
      ENABLE_MODULES: "text2vec-transformers"
      OPENAI_API_KEY: ${openai_token}
      OPENAI_API_BASE: ${openai_endpoint}
      TRANSFORMERS_INFERENCE_API: ${INFERENCE_API_ENDPOINT}
      QUERY_DEFAULTS_LIMIT: "20"
    volumes:
      - weaviate_data:/var/lib/weaviate


volumes:
  weaviate_data:
  db_data:


