"""init migrations

Revision ID: 027eb07e9751
Revises:
Create Date: 2025-04-20 19:29:46.361164

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "027eb07e9751"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("phone", sa.String(), nullable=False),
        sa.Column("subscriber_mts", sa.Boolean(), nullable=False),
        sa.Column("tariff", sa.String(), nullable=False),
        sa.Column("mobile_network", sa.Boolean(), nullable=False),
        sa.Column("home_internet", sa.Boolean(), nullable=False),
        sa.Column("home_tv", sa.Boolean(), nullable=False),
        sa.Column("home_phone", sa.Boolean(), nullable=False),
        sa.Column("device", sa.String(), nullable=False),
        sa.Column("os", sa.String(), nullable=False),
        sa.Column("my_mts_app_user", sa.Boolean(), nullable=False),
        sa.Column("personal_cabinet_user", sa.Boolean(), nullable=False),
        sa.Column("mts_bank_app_user", sa.Boolean(), nullable=False),
        sa.Column("mts_money_app_user", sa.Boolean(), nullable=False),
        sa.Column("subscriptions_services_on_number", sa.Boolean(), nullable=False),
        sa.Column("mts_premium", sa.Boolean(), nullable=False),
        sa.Column("mts_cashback", sa.Boolean(), nullable=False),
        sa.Column("basic_defender", sa.Boolean(), nullable=False),
        sa.Column("defender_plus", sa.Boolean(), nullable=False),
        sa.Column("separate_subscription_kion", sa.Boolean(), nullable=False),
        sa.Column("separate_subscription_music", sa.Boolean(), nullable=False),
        sa.Column("separate_subscription_stroki", sa.Boolean(), nullable=False),
        sa.Column("debit_card_mts_bank", sa.Boolean(), nullable=False),
        sa.Column("credit_card_mts_bank", sa.Boolean(), nullable=False),
        sa.Column("debit_card_mts_money", sa.Boolean(), nullable=False),
        sa.Column("credit_card_mts_money", sa.Boolean(), nullable=False),
        sa.Column("virtual_card_mts_money", sa.Boolean(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    # ### end Alembic commands ###
