"""add dialog

Revision ID: 2551ffc5281a
Revises: 667b8d8d059b
Create Date: 2025-04-21 17:51:26.940404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2551ffc5281a'
down_revision: Union[str, None] = '667b8d8d059b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogs', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('dialogs', 'client_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
