"""add dialog

Revision ID: 667b8d8d059b
Revises: 027eb07e9751
Create Date: 2025-04-21 17:43:20.519941

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '667b8d8d059b'
down_revision: Union[str, None] = '027eb07e9751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.String(), nullable=False),
    sa.Column('subscriber_mts', sa.Boolean(), nullable=False),
    sa.Column('tariff', sa.String(), nullable=False),
    sa.Column('mobile_network', sa.Boolean(), nullable=False),
    sa.Column('home_internet', sa.Boolean(), nullable=False),
    sa.Column('home_tv', sa.Boolean(), nullable=False),
    sa.Column('home_phone', sa.Boolean(), nullable=False),
    sa.Column('device', sa.String(), nullable=False),
    sa.Column('os', sa.String(), nullable=False),
    sa.Column('my_mts_app_user', sa.Boolean(), nullable=False),
    sa.Column('personal_cabinet_user', sa.Boolean(), nullable=False),
    sa.Column('mts_bank_app_user', sa.Boolean(), nullable=False),
    sa.Column('mts_money_app_user', sa.Boolean(), nullable=False),
    sa.Column('subscriptions_services_on_number', sa.Boolean(), nullable=False),
    sa.Column('mts_premium', sa.Boolean(), nullable=False),
    sa.Column('mts_cashback', sa.Boolean(), nullable=False),
    sa.Column('basic_defender', sa.Boolean(), nullable=False),
    sa.Column('defender_plus', sa.Boolean(), nullable=False),
    sa.Column('separate_subscription_kion', sa.Boolean(), nullable=False),
    sa.Column('separate_subscription_music', sa.Boolean(), nullable=False),
    sa.Column('separate_subscription_stroki', sa.Boolean(), nullable=False),
    sa.Column('debit_card_mts_bank', sa.Boolean(), nullable=False),
    sa.Column('credit_card_mts_bank', sa.Boolean(), nullable=False),
    sa.Column('debit_card_mts_money', sa.Boolean(), nullable=False),
    sa.Column('credit_card_mts_money', sa.Boolean(), nullable=False),
    sa.Column('virtual_card_mts_money', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dialogs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.Column('messages', sa.ARRAY(sa.Text()), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('users')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('phone', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('subscriber_mts', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('tariff', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('mobile_network', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('home_internet', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('home_tv', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('home_phone', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('device', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('os', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('my_mts_app_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('personal_cabinet_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mts_bank_app_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mts_money_app_user', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('subscriptions_services_on_number', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mts_premium', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('mts_cashback', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('basic_defender', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('defender_plus', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('separate_subscription_kion', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('separate_subscription_music', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('separate_subscription_stroki', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('debit_card_mts_bank', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('credit_card_mts_bank', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('debit_card_mts_money', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('credit_card_mts_money', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('virtual_card_mts_money', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='users_pkey')
    )
    op.drop_table('dialogs')
    op.drop_table('clients')
    # ### end Alembic commands ###
